### ISSUE TITLE
COAM Service Design Plan

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-coam#1]
To kick off our work on COAM, we'd like to get our initial discovery planning outlined and approved.

This will include:
- [ ] Identify scope of COAM 
- [ ] Identify a timeline for conducting the service design for COAM module
- [ ] Identify activities we want to undertake for planning and where they fall on the timeline
- [ ] Create planning artefact
- [ ] Identify any blockers/dependencies for this work
- [ ] Share with POs/SMEs for feedback
- [ ] Approval by POs/SMEs

**Comment by NicoleGovvy** [comment]
Created duplicate on Moose board.
