### ISSUE TITLE
Define COAM user roles

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-coam#13]
Understand internal and external user roles for COAM needs.

- [x] Identify potential user roles and module activities
- [x] Document on user roles Miro board
- [x] Review with business area + POs

Dependencies: Business Area decision on scope (is/is not matrix), registry process map, and compliance process map, bcgov/cas-obps#267 bcgov/cas-coam#31  bcgov/cas-obps#273 

Reference:
- CATS user roles
- BCCR user roles
- Can users be granted access by operation? (Not just by operator)

**Comment by NicoleGovvy** [comment]
@vesselak Roles are defined for reg part 1 but not finalized for the other modules for both staff/operators. I have updated current state on the BCIERS user roles board. https://miro.com/app/board/uXjVKdOp2dg=/?moveToWidget=3458764602087208888&cot=14

**Comment by NicoleGovvy** [comment]
Business currently working on documentation to support roles/functions, coordinate with for roles grid.

**Comment by patrickisaac** [comment]
Closing ticket as discussed in refinement
