### ISSUE TITLE
What is compliance report part 2

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-coam#35]
Identify what will the compliance report part 2 consist of

**Comment by patriciarussellCAS** [comment]
If this is helpful, here is the language from the regs (section 23)
Compliance report — excess emissions
23.1  In addition to the compliance report required under section 22.1, the operator of a regulated operation, other than a regulated operation that is a new entrant, that had excess emissions in the compliance period must ensure that a report including the following information, as applicable, respecting how the regulated operation met its compliance obligation for the compliance period is submitted to the director:

(a)the amount of the monetary payment made to the government, with proof of payment that the director considers satisfactory;

(b)the number of compliance units made available in a compliance account of the regulated operation for retirement, including the unique identifiers assigned to each compliance unit by the registry administrator;

(c)any other information required by the director.

**Comment by zoeyli-46** [comment]
Thank you @patriciarussellCAS ! because we have that information now, in my opinion, we could close this ticket. (I wasn't aware that it was already outlined in the regs:) ) The only thing left to do is for @nanyangpro to create the high fidelity wireframe. I've already created the low-fidelity wireframe of it and its on Figma [here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20547-5099&t=HWuooErmXEnZX3pZ-4)

**Comment by NicoleGovvy** [comment]
@vesselak @nanyangpro can this ticket be closed?
