### ISSUE TITLE
Show CSNR how all calculations were made

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-coam#38]
CSNR would like a session where they are shown how all the calculations were made, for the purposes of FRCR

**Comment by NicoleGovvy** [comment]
@zoeyli-46  is this still a relevant ticket?

**Comment by zoeyli-46** [comment]
good question! I'll defer to @patriciarussellCAS? I think this was a Giraffe thing

**Comment by NicoleGovvy** [comment]
@vesselak @patriciarussellCAS is this ticket still needed?

**Comment by patriciarussellCAS** [comment]
I don't think we need this ticket. The BA will likely need to explain to Kateryna and MNP how the compliance obligation is calculated but I don't think we need to do anything on our side, so this can be closed. thanks

**Comment by vesselak** [comment]
Closing ticket as no longer required. Obligation ID is of interest for CSNR not the calculation.
