### ISSUE TITLE
Penalties: workflow

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-coam#42]
Penalties can be viewed in COAM. We need to understand the workflow and what happens if a penalty is issued and also reversed to create a user story.

- [x] Document penalty structure with interest
- [x] Understand business process for penalties
- [x] Document penalty user journey (CAS/operator)

**Comment by NicoleGovvy** [comment]
Repurposing ticket as penalties cannot be appealed in COAM. Currently penalties are not finalized by the business area.

**Comment by vesselak** [comment]
Miro board [here](https://miro.com/app/board/uXjVPZNMFas=/?moveToWidget=3458764603701884545&cot=14)

**Comment by NicoleGovvy** [comment]
FAA interest still pending a decision if it will be included or not.

**Comment by patrickisaac** [comment]
Closing ticket as per discussed in standup
