### ISSUE TITLE
Corrections/refunds workflow

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-coam#43]
Understand and diagram the process and needs when an operator has either overpaid and needs to be issued a refund, or has underpaid and needs to make additional payment(s).

- [x] Draft initial workflow
- [x] Share with business/CSNR to refine
- [ ] Iterate/document

**Comment by patrickisaac** [comment]
Closing ticket as discussed in stand up. 

Refunds/Corrections flow board - https://miro.com/app/board/uXjVNyzw5is=/?moveToWidget=3458764602570681264&cot=14
